# Generated by Django 5.0.6 on 2024-05-25 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='email',
            field=models.EmailField(default='email@example.com', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
