# Generated by Django 5.0.6 on 2024-05-25 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp1', '0003_estudiante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='email',
            field=models.EmailField(default='email@example.com', max_length=254),
        ),
    ]
